spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: liuwjg
    password: liuwjg
    url: jdbc:mysql://182.254.183.17/myDb?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell


